// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE

const _VERSION = '0.0.0'; // This value will be overwritten by webpack
const _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;

/**
 * 取得欄位名稱
 * @param obj
 * @param type
 */
export function GET_BASEMODEL_FIELDNAME<T> (obj: any) {
    return new Proxy(obj, {
        get(_, key: string) {
            return key;
        }
    });
}

export const SERVER_URL = '';

export enum MODE_ENUM {
    MAIN = 0, // 清單首頁
    ADD = 1, // 新增
    UPDATE = 2, // 更新
    READ = 3  // 唯讀
}

export enum RETURN_CODE {
    SUCCESSFUL = '000', // 執行成功
    SUCCESS_NO_DATA = '001', // 執行成功，無資料
    SUCCESS_BREAK_POINT_DETECTED = '9000', // 執行成功. 有斷點
    ERROR_NOT_ALLOW_FOR_BUSINESS = '9001', // 執行成功. 產品皆無法申辦
    ALLOW_FOR_BUSINESS = '9002', // 執行成功. 可申辦產品為
    ERROR = '9999', // 執行失敗
}

export enum TRANSACTION_TYPE {
    ACCOUNT = 1,
    CASH = 2
}
